/**
 * @file
 * @author Alexander Van Craen
 * @author Marcel Breyer
 * @copyright 2018-today The PLSSVM project - All Rights Reserved
 * @license This file is part of the PLSSVM project which is released under the MIT license.
 *          See the LICENSE.md file in the project root for full license information.
 *
 * @brief Factory function for constructing a new C-SVM using one of the available backends based on the provided command line arguments.
 */

#ifndef PLSSVM_CSVM_FACTORY_HPP_
#define PLSSVM_CSVM_FACTORY_HPP_
#pragma once

#include "plssvm/backend_types.hpp"          // plssvm::backend
#include "plssvm/csvm.hpp"                   // plssvm::csvm
#include "plssvm/detail/utility.hpp"         // plssvm::detail::remove_cvref_t
#include "plssvm/exceptions/exceptions.hpp"  // plssvm::unsupported_backend_exception
#include "plssvm/parameter.hpp"              // plssvm::parameter
#include "plssvm/target_platforms.hpp"       // plssvm::target_platform

// only include requested/available backends
#if defined(PLSSVM_HAS_OPENMP_BACKEND)
    #include "plssvm/backends/OpenMP/csvm.hpp"  // plssvm::openmp::csvm
#endif
#if defined(PLSSVM_HAS_CUDA_BACKEND)
    #include "plssvm/backends/CUDA/csvm.hpp"  // plssvm::cuda::csvm
#endif
#if defined(PLSSVM_HAS_HIP_BACKEND)
    #include "plssvm/backends/HIP/csvm.hpp"  // plssvm::hip::csvm
#endif
#if defined(PLSSVM_HAS_OPENCL_BACKEND)
    #include "plssvm/backends/OpenCL/csvm.hpp"  // plssvm::opencl::csvm
#endif
#if defined(PLSSVM_HAS_SYCL_BACKEND)
    #include "plssvm/backends/SYCL/implementation_type.hpp"  // plssvm::generic::sycl_implementation_type
    #if defined(PLSSVM_SYCL_BACKEND_HAS_DPCPP)
        #include "plssvm/backends/autogenerated/DPCPP/csvm.hpp"  // plssvm::dpcpp::csvm
    #endif
    #if defined(PLSSVM_SYCL_BACKEND_HAS_HIPSYCL)
        #include "plssvm/backends/autogenerated/hipSYCL/csvm.hpp"  // plssvm::hipsycl::csvm
    #endif
#endif

#include "igor/igor.hpp"  // igor::parser

#include <memory>       // std::unique_ptr, std::make_unique
#include <type_traits>  // std::is_same_v
#include <utility>      // std::forward

namespace plssvm {

// TODO: what if csvm<double> and data_set<float> is given?

/**
 * @brief Create a new C-SVM using the @p backend type and @p target platform. For the remaining C-SVM parameters, the default values are used.
 * @tparam T the floating point type used in the C-SVM
 * @param[in] backend the backend to use
 * @param[in] target the target platform to target
 * @return the C-SVM (`[[nodiscard]]`)
 */

template <typename T>
[[nodiscard]] inline std::unique_ptr<csvm<T>> make_csvm(const backend_type backend) {
    return make_csvm<T>(backend, target_platform::automatic, parameter<T>{});
}
template <typename T>
[[nodiscard]] inline std::unique_ptr<csvm<T>> make_csvm(const backend_type backend, plssvm::parameter<T> params) {
    return make_csvm<T>(backend, target_platform::automatic, params);
}
template <typename T>
[[nodiscard]] inline std::unique_ptr<csvm<T>> make_csvm(const backend_type backend, const target_platform target) {
    return make_csvm<T>(backend, target, parameter<T>{});
}

/**
 * @brief Create a new C-SVM using the @p backend type, @p target platform, and @p params. Additional parameters (e.g., SYCL specific parameters) are provided via @p args.
 * @details Converts the @p params value to the respective named-parameter calls.
 * @tparam T the floating point type used in the C-SVM
 * @tparam Args the type of the potential additional parameters
 * @param[in] backend the backend to use
 * @param[in] target the target platform to target
 * @param[in] params the SVM parameters to use
 * @param[in] args possible additional parameters (e.g., the SYCL implementation type if and only if the @p backend is SYCL)
 * @return the C-SVM (`[[nodiscard]]`)
 */
template <typename T>
[[nodiscard]] inline std::unique_ptr<csvm<T>> make_csvm(const backend_type backend, const target_platform target, const parameter<T> params) {
    return make_csvm<T>(backend, target, params.kernel_type, plssvm::degree = params.degree, plssvm::gamma = params.gamma, plssvm::coef0 = params.coef0, plssvm::cost = params.cost);
} // TODO: führt zu warnungen in base csvm Konstruktor führen

/**
 * @brief Create a new C-SVM using the @p backend type, @p target platform, @p kernel type, and potential additional named-parameter @p args.
 * @tparam T the floating point type used in the C-SVM
 * @tparam Args the type of the potential named-parameter
 * @param[in] backend the backend to use
 * @param[in] target the target platform to target
 * @param[in] kernel the kernel function to use
 * @param[in] args possible additional parameters (e.g., degree parameter for the polynomial kernel)
 * @return the C-SVM (`[[nodiscard]]`)
 */
template <typename T, typename... Args>
[[nodiscard]] std::unique_ptr<csvm<T>> make_csvm(const backend_type backend, const target_platform target, const kernel_function_type kernel, Args &&...args) {
    switch (backend) {
        case backend_type::automatic:
            return make_csvm<T>(determine_default_backend(), target, kernel, std::forward<Args>(args)...);
        case backend_type::openmp:
#if defined(PLSSVM_HAS_OPENMP_BACKEND)
            return std::make_unique<openmp::csvm<T>>(target, kernel, std::forward<Args>(args)...);
#else
            throw unsupported_backend_exception{ "No OpenMP backend available!" };
#endif

        case backend_type::cuda:
#if defined(PLSSVM_HAS_CUDA_BACKEND)
            return std::make_unique<cuda::csvm<T>>(target, kernel, std::forward<Args>(args)...);
#else
            throw unsupported_backend_exception{ "No CUDA backend available!" };
#endif

        case backend_type::hip:
#if defined(PLSSVM_HAS_HIP_BACKEND)
            return std::make_unique<hip::csvm<T>>(target, kernel, std::forward<Args>(args)...);
#else
            throw unsupported_backend_exception{ "No HIP backend available!" };
#endif

        case backend_type::opencl:
#if defined(PLSSVM_HAS_OPENCL_BACKEND)
            return std::make_unique<opencl::csvm<T>>(target, kernel, std::forward<Args>(args)...);
#else
            throw unsupported_backend_exception{ "No OpenCL backend available!" };
#endif

        case backend_type::sycl:
#if defined(PLSSVM_HAS_SYCL_BACKEND)
        {
            // check igor parameter
            igor::parser parser{ args... };

            sycl_generic::implementation_type impl_type = sycl_generic::implementation_type::automatic;
            // check whether a specific SYCL implementation type has been requested
            if constexpr (parser.has(sycl_implementation_type)) {
                // compile time check: the value must have the correct type
                static_assert(std::is_same_v<detail::remove_cvref_t<decltype(parser(sycl_implementation_type))>, sycl_generic::implementation_type>, "sycl_implementation_type must be convertible to a plssvm::sycl::implementation_type!");
                impl_type = static_cast<sycl_generic::implementation_type>(parser(sycl_implementation_type));
            }
            switch (impl_type) {
                case sycl_generic::implementation_type::automatic:
                    return std::make_unique<PLSSVM_SYCL_BACKEND_PREFERRED_IMPLEMENTATION::csvm<T>>(target, kernel, std::forward<Args>(args)...);
                case sycl_generic::implementation_type::dpcpp:
    #if defined(PLSSVM_SYCL_BACKEND_HAS_DPCPP)
                    return std::make_unique<dpcpp::csvm<T>>(target, kernel, std::forward<Args>(args)...);
    #else
                    throw unsupported_backend_exception{ "No SYCL backend using DPC++ available!" };
    #endif
                case sycl_generic::implementation_type::hipsycl:
    #if defined(PLSSVM_SYCL_BACKEND_HAS_HIPSYCL)
                    return std::make_unique<hipsycl::csvm<T>>(target, kernel, std::forward<Args>(args)...);
    #else
                    throw unsupported_backend_exception{ "No SYCL backend using hipSYCL available!" };
    #endif
            }
        }
#else
            throw unsupported_backend_exception{ "No SYCL backend available!" };
#endif
    }
    throw unsupported_backend_exception{ "Can't recognize backend !" };
}

}  // namespace plssvm

#endif  // PLSSVM_CSVM_FACTORY_HPP_
