#!groovy
pipeline {
    agent { label 'pcsgs05' }
    stages {
        stage('checkout') {
            steps {
                dir('plssvm') {
                    checkout scm
                }
            }
        }
        stage('setup python'){
            steps{
                sh '''
                    /usr/bin/python3.8 -m pip install --user arff
                    /usr/bin/python3.8 -m pip install --user pandas
                    /usr/bin/python3.8 -m pip install --user sklearn
                '''
            }
        }
        stage('build plssvm') {
            steps {
                dir('plssvm') {
                    sh '''
                        module load cuda
                        echo $PWD
                        cd SVM
                        mkdir -p build/Release
                        cd build/Release
                        /import/sgs.scratch/vancraar/spack/opt/spack/linux-ubuntu20.04-cascadelake/clang-12.0.0/cmake-3.20.2-z3urlvzqm5igtwxj25nnd5olciuq7ayb/bin/cmake -DCMAKE_BUILD_TYPE=Relese ../../
                        make -j4
                    '''
                }
            }
        }
        stage('run tests') {
            steps {
                dir('plssvm') {
                    sh '''
                        module load cuda
                        cd SVM
                        git checkout 873c8e0efbe8563ab0a688d297f0720998e9304b -- platform_configuration.cfg
                        cd build/Release
                        ctest -j4
                    '''
                }
            }
        }
    }
}