/**
 * @author Alexander Van Craen
 * @author Marcel Breyer
 * @copyright 2018-today The PLSSVM project - All Rights Reserved
 * @license This file is part of the PLSSVM project which is released under the MIT license.
 *          See the LICENSE.md file in the project root for full license information.
 *
 * @brief Tests for the OpenCL backend device pointer.
 */

#include "plssvm/backends/autogenerated/@PLSSVM_SYCL_BACKEND_INCLUDE_NAME@/detail/device_ptr.hpp"
#include "plssvm/backends/SYCL/detail/constants.hpp"  // forward declaration and namespace alias

#include "plssvm/backends/autogenerated/@PLSSVM_SYCL_BACKEND_INCLUDE_NAME@/detail/queue_impl.hpp"

#include "backends/generic_device_ptr_tests.h"

#include "sycl/sycl.hpp"  // sycl::queue

#include "gtest/gtest.h"  // INSTANTIATE_TYPED_TEST_SUITE_P, ::testing::Types

#include <memory>  // std::unique_ptr

template <typename T>
struct device_ptr_test_type {
    using device_ptr_type = plssvm::@PLSSVM_SYCL_BACKEND_NAMESPACE_NAME@::detail::device_ptr<T>;
    using queue_type = plssvm::@PLSSVM_SYCL_BACKEND_NAMESPACE_NAME@::detail::queue;

    static const queue_type &default_queue() {
        static queue_type queue{ std::make_unique<plssvm::@PLSSVM_SYCL_BACKEND_NAMESPACE_NAME@::detail::queue::queue_impl>() };
        return queue;
    }
};

using device_ptr_test_types = ::testing::Types<
    device_ptr_test_type<float>,
    device_ptr_test_type<double>>;

// instantiate type-parameterized tests
INSTANTIATE_TYPED_TEST_SUITE_P(@PLSSVM_SYCL_BACKEND_INCLUDE_NAME@Backend, DevicePtr, device_ptr_test_types);
INSTANTIATE_TYPED_TEST_SUITE_P(@PLSSVM_SYCL_BACKEND_INCLUDE_NAME@BackendDeathTest, DevicePtrDeathTest, device_ptr_test_types);