name: macOS CPU
on:
  workflow_dispatch:
  push:
jobs:
  macOS-Test:
    runs-on: macos-13
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: "Install cmake 3.31.0"
        uses: lukka/get-cmake@v3.31.0
      - name: "Install LLVM and Clang"
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "15.0"
      - name: "Install dependencies via brew"
        run: |
          brew install python3
          brew install numpy
          brew install libomp
      - name: "Install Python dependencies"
        run: |
          python3 -m pip install argparse scikit-learn humanize --break-system-packages
      - name: "Clone the PLSSVM repository into PLSSVM/"
        uses: actions/checkout@v4.1.1
        with:
          path: PLSSVM
      - name: "Configure PLSSVM using CMake"
        run: |
          cd PLSSVM
          export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
          cmake --preset openmp_test -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DPLSSVM_TARGET_PLATFORMS="cpu" -DPLSSVM_ENABLE_LANGUAGE_BINDINGS=ON -DPLSSVM_ENABLE_PERFORMANCE_TRACKING=ON -DPLSSVM_GENERATE_TEST_FILE=OFF -DPLSSVM_ENABLE_LTO=OFF
      - name: "Build PLSSVM"
        shell: bash
        run: |
          cd PLSSVM
          export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
          cmake --build --preset openmp_test --config ${{ matrix.build_type }}
          echo "${GITHUB_WORKSPACE}/PLSSVM/build" >> $GITHUB_PATH
      - name: "Run tests"
        run: |
          cd PLSSVM
          export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
          ctest --preset openmp_test -C ${{ matrix.build_type }} -E ".*executable.*" --parallel 2
