name: macOS CPU
on: push
jobs:
  macOS-Test:
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: "Install cmake 3.28.3"
        uses: lukka/get-cmake@v3.28.3
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "15.0"
      - name: "Install dependencies via brew"
        run: |
          brew install python3
          brew install numpy
          brew install libomp
      - name: "Install Python dependencies"
        run: |
          python3 -m pip install argparse scikit-learn humanize --break-system-packages
      - name: "Clone the PLSSVM repository into PLSSVM/"
        uses: actions/checkout@v4.1.1
        with:
          path: PLSSVM
      - name: "Configure PLSSVM using CMake"
        run: |
          mkdir PLSSVM/build
          cd PLSSVM/build
          export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
          cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DPLSSVM_TARGET_PLATFORMS="cpu" -DPLSSVM_ENABLE_ASSERTS=ON -DPLSSVM_ENABLE_LANGUAGE_BINDINGS=ON -DPLSSVM_ENABLE_PERFORMANCE_TRACKING=ON -DPLSSVM_ENABLE_TESTING=ON -DPLSSVM_TEST_FILE_NUM_DATA_POINTS=50 -DPLSSVM_TEST_FILE_NUM_FEATURES=20 -DPLSSVM_ENABLE_LTO=OFF -DPLSSVM_ENABLE_FAST_MATH=OFF -DPLSSVM_ENABLE_OPENCL_BACKEND=OFF ..
      - name: "Build PLSSVM"
        shell: bash
        run: |
          cd PLSSVM/build
          export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
          cmake --build . --config ${{ matrix.build_type }}
          echo "${GITHUB_WORKSPACE}/PLSSVM/build" >> $GITHUB_PATH
      - name: "Run tests"
        run: |
          cd PLSSVM/build
          export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
          ctest -j 2 -E ".*executable.*" --output-on-failure -C ${{ matrix.build_type }}
