name: Generate documentation

# only trigger this action on specific events
on:
  push:
    branches:
      - main
      - documentation
  pull_request:
    branches:
      - main

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - name: "Checkout PLSSVM"
        uses: actions/checkout@v4.1.1
        with:
          path: PLSSVM
      # install dependencies
      - name: "Dependencies"
        run: |
          sudo apt update
          sudo apt-get install -y doxygen graphviz
      # install new CMake version
      - name: "Install cmake 3.31.0"
        uses: lukka/get-cmake@v3.31.0
      # configure project via CMake
      - name: "Configure"
        run: |
          cd PLSSVM
          cmake --preset openmp -DPLSSVM_TARGET_PLATFORMS="cpu" -DPLSSVM_ENABLE_DOCUMENTATION=ON
      # build project
      - name: "Generate"
        run: |
          cd PLSSVM
          cmake --build --preset openmp --target doc
      # deploy generated documentation using github.io
      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./PLSSVM/docs/html
