name: Generate documentation

# only trigger this action on specific events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - name: Checkout PLSSVM
        uses: actions/checkout@v2
        with:
          path: PLSSVM

      # mimic CMake's configure step for current setup
      - name: Configure
        run: |
          cd PLSSVM
          mkdir build
          cd build
          sudo apt-get install -y doxygen graphviz
          cmake -DPLSSVM_TARGET_PLATFORMS=cpu -DPLSSVM_ENABLE_DOCUMENTATION=ON ..
          make doc
      # deploy generated documentation using github.io
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .PLSSVM/doc/html
