name: Windows MSVC CPU
on:
  workflow_dispatch:
  push:
jobs:
  MSVC-Test:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: "Install latest MSVC compiler"
        uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: "Install cmake 3.31.0"
        uses: lukka/get-cmake@v3.31.0
      - name: "Clone the PLSSVM repository into PLSSVM/"
        uses: actions/checkout@v4.1.1
        with:
          path: PLSSVM
      - name: "Install Python dependencies"
        run: |
          py -m pip install --upgrade pip setuptools wheel
          py -m pip install -r PLSSVM/install/python_requirements.txt
      - name: "Configure PLSSVM using CMake"
        run: |
          cd PLSSVM
          cmake --preset openmp_test -DCMAKE_CONFIGURATION_TYPES=${{ matrix.build_type }} -DPLSSVM_TARGET_PLATFORMS="cpu" -DPLSSVM_ENABLE_LANGUAGE_BINDINGS=ON -DPLSSVM_ENABLE_PERFORMANCE_TRACKING=ON -DPLSSVM_TEST_FILE_NUM_DATA_POINTS=50 -DPLSSVM_TEST_FILE_NUM_FEATURES=20
      - name: "Build PLSSVM"
        shell: bash
        run: |
          cd PLSSVM
          cmake --build --preset openmp_test --config ${{ matrix.build_type }}
          echo "${GITHUB_WORKSPACE}/PLSSVM/build" >> $GITHUB_PATH
      - name: "Run tests"
        run: |
          cd PLSSVM
          ctest --preset openmp_test -C ${{ matrix.build_type }} -E ".*executable.*" --parallel 2
